name: ci

on:
  push:
    branches:
      - 'master'
      - 'github-action'

jobs:
  docker:
    runs-on: ubuntu-latest
    strategy:
      matrix:
       include:
         - name: nginx-pagespeed
           folder: ningx-pagespeed
           arch: [ linux/amd64 ]

         - name: php72-cli
           folder: php/7.2/cli
           arch: [ linux/amd64, linux/arm64 ]

         - name: php72-fpm
           folder: php/7.2/cli
           arch: [ linux/amd64, linux/arm64 ]

    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ${{ matrix.folder }}
          platforms: ${{ join(matrix.arch, ',') }}
          push: true
          tags: phpdockerio/${{ matrix.name }}:latest
