name: build-all-containers

on:
  push:
    branches:
      - "master"
      - "github-action"

jobs:
  docker:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - name: nginx-pagespeed
            folder: nginx-pagespeed
            arch: [linux/amd64]
            targets:
              primary: ~
              secondary: ~
              tertiary: ~

          - name: php72
            folder: php/7.2
            arch: [linux/amd64, linux/arm64]
            targets:
              primary: cli
              secondary: fpm
              tertiary: ~

          - name: php73
            folder: php/7.3
            arch: [linux/amd64, linux/arm64]
            targets:
              primary: cli
              secondary: fpm
              tertiary: ~

          - name: php74
            folder: php/7.4
            arch: [linux/amd64, linux/arm64]
            targets:
              primary: cli
              secondary: fpm
              tertiary: swoole

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push primary container
        uses: docker/build-push-action@v2
        with:
          context: ${{ matrix.folder }}
          platforms: ${{ join(matrix.arch, ',') }}
          push: true
          tags: phpdockerio/${{ matrix.targets.primary && format('{0}-{1}', matrix.name, matrix.targets.primary) || matrix.name }}:latest
          target: ${{ matrix.targets.primary }}
          cache-from: type=registry,ref=phpdockerio/${{ matrix.targets.primary && format('{0}-{1}', matrix.name, matrix.targets.primary) || matrix.name }}:buildcache
          cache-to: type=registry,ref=phpdockerio/${{ matrix.targets.primary && format('{0}-{1}', matrix.name, matrix.targets.primary) || matrix.name }}:buildcache,mode=max

      - name: Build and push secondary container
        if: matrix.targets.secondary
        uses: docker/build-push-action@v2
        with:
          context: ${{ matrix.folder }}
          platforms: ${{ join(matrix.arch, ',') }}
          push: true
          tags: phpdockerio/${{ format('{0}-{1}', matrix.name, matrix.targets.secondary) }}:latest
          target: ${{ matrix.targets.secondary }}
          cache-from: type=registry,ref=phpdockerio/${{ format('{0}-{1}', matrix.name, matrix.targets.secondary) }}:buildcache
          cache-to: type=registry,ref=phpdockerio/${{ format('{0}-{1}', matrix.name, matrix.targets.secondary) }}:buildcache,mode=max

      - name: Build and push tertiary container
        if: matrix.targets.tertiary
        uses: docker/build-push-action@v2
        with:
          context: ${{ matrix.folder }}
          platforms: ${{ join(matrix.arch, ',') }}
          push: true
          tags: phpdockerio/${{ format('{0}-{1}', matrix.name, matrix.targets.tertiary) }}:latest
          target: ${{ matrix.targets.tertiary }}
          cache-from: type=registry,ref=phpdockerio/${{ format('{0}-{1}', matrix.name, matrix.targets.tertiary) }}:buildcache
          cache-to: type=registry,ref=phpdockerio/${{ format('{0}-{1}', matrix.name, matrix.targets.tertiary) }}:buildcache,mode=max
